[project]
name = "tqdm-demo"
version = "0.1.0"
description = "A demo project for tqdm"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.10.0",
    "tqdm>=4.67.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
